services:
  db:
    image: postgres:16
    container_name: gpri_db
    environment:
      POSTGRES_DB: payments_risk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments_risk"]
      interval: 5s
      timeout: 5s
      retries: 10

  ingestion:
    build:
      context: ./services/ingestion
    container_name: gpri_ingestion
    environment:
      POSTGRES_DB: payments_risk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      WORLD_BANK_INDICATORS: "FX.OWN.TOTL.ZS,FX.OWN.TOTL.DT.ZS,FX.OWN.TOTL.MM.ZS,FB.CBK.BRCH.P5"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
